### PR TITLE
Ar 59 auto generate four year plan

### PR DESCRIPTION
**Pull request by ruudkas**
Here is auto generate four year plan. I have checked all of the four year plans and they appear to be working now that MATH-180 exists in the database. They are properly updating the credit count for each semester along with the credit warning and display all of the courses. The courses can drag between semesters and the course list without any issues. 

Pre-reqs are not checked when the courses are added because it is assumed that the four-year-plan follows pre-reqs. The requirements are automatically updated when the schedule is updated.

### CODE REVIEW

**Review by Tyler-Pamperin — APPROVED** [review]
All seems to be working. 👍

**Comment by ChrisVasterling** [comment]
Do we want to consider completed courses when generating the four year plan? I noticed that when adding ENGL-101 as a completed course, it wasn't removed from the semester.

**Comment by ruudkas** [comment]
> Do we want to consider completed courses when generating the four year plan? I noticed that when adding ENGL-101 as a completed course, it wasn't removed from the semester.

I realized that a little bit ago, should be like a two line fix but my laptops dead so I’ll do it before architecture in the morning.

**Comment by Tyler-Pamperin** [comment]
> > Do we want to consider completed courses when generating the four year plan? I noticed that when adding ENGL-101 as a completed course, it wasn't removed from the semester.
> 
> I realized that a little bit ago, should be like a two line fix but my laptops dead so I’ll do it before architecture in the morning.

I did it quick, and in one line of code instead of two 😎

**Review by ChrisVasterling — APPROVED** [review]
looks good to me

**Pull request merged**
