### PR TITLE
AR-110 incorporate gen-eds

### PR DESCRIPTION
**Pull request by ChrisVasterling**
Gen-ed categories/courses have been added. There is a test for the new endpoint, but not for the front end due to the drag and drop testing problems.

### CODE REVIEW

**Review by Tyler-Pamperin — APPROVED** [review]
Looks good to me, although I did notice some gen ed data credit's seems incorrect. If you wanna look into that and see what may be happening, that would be epic
image

**Comment by ChrisVasterling** [comment]
> Looks good to me, although I did notice some gen ed data's credits seems incorrect. If you wanna look into that and see what may be happening, that would be epic 

Those credits look a bit odd because when collecting data I was taking the minimum value for credits whenever there was a range. Fixing them should be as easy as updating the value in the database. 
https://bulletin.uwstout.edu/preview_program.php?catoid=21&poid=4438
image
image

**Review by ruudkas — APPROVED** [review]
It's not all of the info we need about each course, but it matches what's in main and I've already updated it on my branch so I suppose it's adequate. Although the fact that the courses don't always appear sorted by subject bothers me.

**Comment by ChrisVasterling** [comment]
> It's not all of the info we need about each course, but it matches what's in main and I've already updated it on my branch so I suppose it's adequate. Although the fact that the courses don't always appear sorted by subject bothers me.

I could add an `ORDER BY` at the end of the SQL queries that get courses

**Comment by ruudkas** [comment]
> I could add an `ORDER BY` at the end of the SQL queries that get courses
If it's easy go for it, it just makes it slightly more challenging to find a specific course but it's certainly usable without it.

**Pull request merged**
