### PR TITLE
Fixed incorrect prereq error message bug

### PR DESCRIPTION
**Pull request by Tyler-Pamperin**
Fixed bug where moving a course unrelated to another course with failed prereqs would say that the unrelated course was a prereq for the failed course.

ex. MSCS_200 is missing prereq CS_144 
The user moves the course ENG_L101 out of the semesters.
The error message used to say "ENGL_101 is a prerequisite for the following courses: MSCS_200"; now the error message will not even show up.

### CODE REVIEW

**Comment by ruudkas** [comment]
Moving Engl-101 to a semester after ENGL-102 didn't have any error message(it did turn red). Then when I moved ENGL-101 back to before ENGL-102 it didn't change back to normal.
image

**Comment by ruudkas** [comment]
Similar issue, if you move a course around a lot it doesn't always set the right color:
image

**Review by ChrisVasterling — APPROVED** [review]
Seems to be working

**Review by ruudkas — APPROVED** [review]
Looks like most bugs have been fixed, nice job!

**Pull request merged**
