### PR TITLE
Bug fix

### PR DESCRIPTION
**Pull request by ruudkas**
The export was using a null concentration because it was set to null to fix an earlier bug and had to be placed into an if statement.

### CODE REVIEW

**Comment by Raffeln6264** [comment]
Awesome, there are dinosaurs in this PR!

**Review by ChrisVasterling — APPROVED** [review]
lgtm

**Review by kreklb — COMMENTED** [review]
Thanks!

**Review by Tyler-Pamperin — APPROVED** [review]

**Comment by Raffeln6264** [comment]
The Spinosaurus is the best Dinosaur, believe it or not.

**Review by kreklb — APPROVED** [review]

**Review by Raffeln6264 — APPROVED** [review]
LGTM.

**Pull request merged**
