### PR TITLE
AR-125 display completed courses & AR-129 Four Year Plan Requirements

### PR DESCRIPTION
**Pull request by ChrisVasterling**
This includes changes from AR-125 and AR-129.

### CODE REVIEW

**Review by ruudkas — APPROVED** [review]
Looks good once merge conflicts are dealt with.

Just noting for the sake of documentation: We don't remove requirements from the four year plan section of the drop down when they are filled (too much work with the time remaining)

**Comment by ChrisVasterling** [comment]
The styling for completed courses in InputPage seems to be off, not sure if this was from my merge or from Shane's styling

**Comment by ruudkas** [comment]
> The styling for completed courses in InputPage seems to be off, not sure if this was from my merge or from Shane's styling

I don't know who it was but it definitely has issues

**Review by Tyler-Pamperin — APPROVED** [review]
Drop target big chungus

**Pull request merged**
