### PR TITLE
AR-78 Completed course dropdown

### PR DESCRIPTION
**Pull request by ruudkas**

### CODE REVIEW

**Review by ChrisVasterling — APPROVED** [review]
Looks good to me

**Comment by ruudkas** [comment]
> Looks good to me

image
Well, the page doesn't render for me. Any ideas?

**Comment by ChrisVasterling** [comment]
> > Looks good to me
> 
> image Well, the page doesn't render for me. Any ideas?

That image shows that the error happened on line 56 of SearchableDropdown.tsx but there are only 38 lines in that file in this branch

**Comment by ruudkas** [comment]
> > > Looks good to me
> > 
> > 
> > image Well, the page doesn't render for me. Any ideas?
> 
> That image shows that the error happened on line 56 of SearchableDropdown.tsx but there are only 38 lines in that file in this branch

I'm trying to merge in main, it only showed conflicts in the app.js file, let me cancel the merge test it and try again.

**Comment by ruudkas** [comment]
So the actual code works but the tests are now broken because the dropdowns have no data.

**Comment by ChrisVasterling** [comment]
image
Performing this null check on props.options makes the tests pass. if props.options is null `.map()` is never run.

**Pull request merged**
